### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by THEXN** [itsFrankV22/EssentialsPlus-ES-EN-x64#1]
Este plugin ya soporta i18n en nuestra biblioteca de plugins. He completado las traducciones al chino y al inglés, y he preparado un archivo .po para es-ES. Si está interesado, puede usar Poedit para editar este archivo y ayudarnos con la traducción. Además, puede enviar un README_ES.md. ¡Gracias por su ayuda y colaboración! [https://github.com/UnrealMultiple/TShockPlugin/blob/master/src/EssentialsPlus/README_EN.md](url)

**Comment by itsFrankV22** [comment]
OK, I will work on that from now on

**Comment by itsFrankV22** [comment]
Hello, I'm the one who contacted you to translate the plugin into Spanish, contact me on Discord to tell me what to do, the i18n you gave me to translate is in this repository

**Comment by itsFrankV22** [comment]
contact me with the discord that is in my profile
